# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-PopupWindow
version:      0.05
version_from: lib/Gtk2/Ex/PopupWindow.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Glib:                          0
    Gtk2:                          0
    Gtk2::TestHelper:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
